# Generated by Django 4.0.4 on 2022-05-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_review_product_alter_review_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('product', 'date_update'), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='date_create',
        ),
        migrations.AddField(
            model_name='review',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата отзыва'),
        ),
    ]
