# Generated by Django 4.0.4 on 2022-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_review_options_remove_review_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата отзыва'),
        ),
    ]
