# Generated by Django 4.0.4 on 2022-05-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар'),
        ),
    ]
