# Generated by Django 4.0.4 on 2022-06-01 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_basketrecord_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Добавлен'),
            preserve_default=False,
        ),
    ]
